apiVersion: v1
kind: Pod
metadata:
  name: init-pod
spec:
  initContainers:
    - name: init-container1
      image: alpine:3
      command:
        - sleep
        - "30"
    - name: init-container2
      image: alpine:3
      command:
        - sleep
        - "30"  
  containers:
    - name: nginx-container
      image: nginx:stable-alpine3.19-perl
      ports:
        - containerPort: 80
          protocol: TCP 
