apiVersion: v1
kind: ReplicationController
metadata:
  name: replication-demo
  labels:
    app: nginx
spec:
  minReadySeconds: 5
  replicas: 2
  selector: 
      app: nginx
  template:
    metadata: 
      labels:
        app: nginx
    spec:
      containers: 
        - name: nginx
          image: nginx:stable-alpine3.19-perl    
          ports:
            - containerPort: 80
              protocol: TCP