apiVersion: v1	
kind: Service
metadata:
  name: service-pod
  lables:
    app: server-service
spec:
  selector:
    app: server-service
  ports: 
    - name: nginx
      port: 80
      protocol: TCP
      targetPort: 5555 
    